name: Chocolatey Safe Install

on:
  workflow_dispatch:

jobs:
  setup-chocolatey:
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - name: 安全安装Chocolatey
        shell: pwsh
        run: |
          # 环境初始化
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072

          # 分阶段安装函数
          function Install-Chocolatey {
              param([string]$version)
              
              # 首次安装
              if (-not (Test-Path "$env:ProgramData\chocolatey\choco.exe")) {
                  Write-Output "执行全新安装..."
                  $installScript = {
                      iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
                      if (-not (Test-Path "$env:ProgramData\chocolatey\choco.exe")) {
                          throw "安装失败：无法找到choco.exe"
                      }
                  }
                  & $installScript
              }

              # 版本管理
              $currentVersion = try { (choco --version 2>$null) } catch { $null }
              if ($currentVersion -and [version]$currentVersion -ne [version]$version) {
                  Write-Output "当前版本 $currentVersion → 目标版本 $version"
                  choco upgrade chocolatey --version=$version -y --force --no-progress
              }

              # 环境刷新
              $env:Path = [System.Environment]::GetEnvironmentVariable('Path','Machine') + ";" + [System.Environment]::GetEnvironmentVariable('Path','User')
          }

          # 执行安装流程
          Install-Chocolatey -version "2.4.3"

          # 验证安装结果
          choco --version
          if (-not $?) { exit 1 }
