name: "RustDesk Windows CI (Stable)"

on:
  workflow_dispatch:
    inputs:
      clean_install:
        description: "Full clean install"
        type: boolean
        default: false

env:
  VCPKG_ROOT: "C:\\vcpkg"
  VCPKG_BINARY_SOURCES: "clear;default,readwrite"  # 修复缓存配置
  VCPKG_FEATURE_FLAGS: "-versions,-manifests"      # 禁用问题功能

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 60

    steps:
    - name: "1️⃣ Clean Workspace"
      if: ${{ inputs.clean_install }}
      shell: powershell
      run: |
        Remove-Item -Recurse -Force "$env:VCPKG_ROOT" -ErrorAction SilentlyContinue
        Remove-Item -Recurse -Force "target" -ErrorAction SilentlyContinue

    - name: "2️⃣ Checkout Code"
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: "3️⃣ Setup vcpkg"
      shell: powershell
      run: |
        if (-not (Test-Path "$env:VCPKG_ROOT\vcpkg.exe")) {
          git clone https://github.com/microsoft/vcpkg "$env:VCPKG_ROOT"
          & "$env:VCPKG_ROOT\bootstrap-vcpkg.bat" -disableMetrics
        }
        echo "$env:VCPKG_ROOT" >> $env:GITHUB_PATH

    - name: "4️⃣ Install Dependencies (Fixed)"
      shell: powershell
      run: |
        & "$env:VCPKG_ROOT\vcpkg" install @(
          "libvpx",
          "libyuv",
          "openssl"
        ) --triplet x64-windows `
          --clean-after-build `
          --recurse `
          --x-asset-sources=clear `
          --x-no-default-features

    - name: "5️⃣ Build Project"
      shell: powershell
      run: |
        cargo build --release --target x86_64-pc-windows-msvc
